name: gun_core_flutter
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.1

# # Add regular dependencies here.
# dependencies:
#   # path: ^1.8.0
#   permission_handler: ^12.0.0+1
#   flutter_svg: ^2.2.1
#   flutter_screenutil: ^5.9.3
#   flutter_bloc: ^9.1.1
#   go_router: ^16.2.5
#   flutter_form_builder: ^10.0.1
#   modal_bottom_sheet: ^3.0.0
#   form_builder_validators: ^11.0.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
