name: gun_core_flutter
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  permission_handler: ^12.0.0+1
  flutter_svg: ^2.0.16
  flutter_screenutil: ^5.9.3
  flutter_bloc: ^8.1.6
  go_router: ^14.6.2

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
